apiVersion: v1
kind: Service
metadata:
  name: young-moscow-server-service
spec:
  selector:
    app: young-moscow-server
  ports:
  - protocol: TCP
    port: 12345
    targetPort: 12345
  type: LoadBalancer
